
DVAR $hFile
DVAR $cCheck
DVAR $press
DVAR $length
DVAR $lame
DVAR $comport
DVAR $vacpress

$DO0.0=0
$DO1.0=0
$DO2.0=0
$DO3.0=0

Primary ; sets primary units mm and s
G65 F2000; accel speed mm/s^2
G66 F2000;accel speed mm/s^2

Call setPress P5 Q40.0 ; tool 0

G90 ;use absolute coordinates 
MINUTES

; generated by Slic3r 1.3.0 on 2022-08-20 at 19:35:08

; external perimeters extrusion width = 0.25mm (0.34mm^3/s)
; perimeters extrusion width = 0.25mm (0.34mm^3/s)
; infill extrusion width = 0.25mm (0.05mm^3/s)
; solid infill extrusion width = 0.25mm (0.98mm^3/s)
; top infill extrusion width = 0.25mm (0.74mm^3/s)



 ; set units to millimeters
G90 ; use absolute coordinates

 ; reset extrusion distance
G1 Z0.250 F600.000 ; move to next layer (0)

 ; reset extrusion distance
G1 Z10.250 F600.000 ; lift Z
G1 X5.681 Y-1.527 F600.000 ; move to first infill point
G1 Z0.250 F600.000 ; restore layer Z

G1 F60
G1 X31.652 Y-1.527 E2.06493 ; infill
G1 X31.652 Y-1.745 E2.06547 ; infill
G1 X7.287 Y-1.745 E2.12638 ; infill
G1 X8.197 Y-1.963 E2.12873 ; infill
G1 X31.652 Y-1.963 E2.18736 ; infill
G1 X31.652 Y-2.182 E2.18791 ; infill
G1 X8.903 Y-2.182 E2.24478 ; infill
G1 X9.497 Y-2.400 E2.24636 ; infill
G1 X31.652 Y-2.400 E2.30175 ; infill
G1 X31.652 Y-2.618 E2.30229 ; infill
G1 X10.013 Y-2.618 E2.35639 ; infill
G1 X10.472 Y-2.836 E2.35766 ; infill
G1 X31.652 Y-2.836 E2.41061 ; infill
G1 X31.652 Y-3.054 E2.41116 ; infill
G1 X10.888 Y-3.054 E2.46306 ; infill
G1 X11.271 Y-3.272 E2.46417 ; infill
G1 X31.652 Y-3.272 E2.51512 ; infill
G1 X31.652 Y-3.491 E2.51566 ; infill
G1 X11.628 Y-3.491 E2.56572 ; infill
G1 X11.963 Y-3.709 E2.56672 ; infill
G1 X31.652 Y-3.709 E2.61594 ; infill
G1 X31.652 Y-3.927 E2.61649 ; infill
G1 X12.271 Y-3.927 E2.66494 ; infill
G1 X12.563 Y-4.145 E2.66585 ; infill
G1 X31.652 Y-4.145 E2.71357 ; infill
G1 X31.652 Y-4.363 E2.71412 ; infill
G1 X12.842 Y-4.363 E2.76114 ; infill
G1 X13.100 Y-4.581 E2.76199 ; infill
G1 X31.652 Y-4.581 E2.80837 ; infill

 ; reset extrusion distance
G1 Z10.250 F600.000 ; lift Z
G1 X13.1000 Y4.5810 F600.000 ; move to first infill point
G1 Z0.250 F600.000 ; restore layer Z

G1 F60
Call togglePress P5; toggle on
G1 X31.6520 Y4.5810 ; infill
G1 X31.6520 Y4.3630 ; infill
G1 X12.8420 Y4.3630 ; infill
G1 X12.5630 Y4.1450 ; infill
G1 X31.6520 Y4.1450 ; infill
G1 X31.6520 Y3.9270 ; infill
G1 X12.2710 Y3.9270 ; infill
G1 X11.9630 Y3.7090 ; infill
G1 X31.6520 Y3.7090 ; infill
G1 X31.6520 Y3.4910 ; infill
G1 X11.6280 Y3.4910 ; infill
G1 X11.2710 Y3.2720 ; infill
G1 X31.6520 Y3.2720 ; infill
G1 X31.6520 Y3.0540 ; infill
G1 X10.8880 Y3.0540 ; infill
G1 X10.4720 Y2.8360 ; infill
G1 X31.6520 Y2.8360 ; infill
G1 X31.6520 Y2.6180 ; infill
G1 X10.0130 Y2.6180 ; infill
G1 X9.4970 Y2.4000 ; infill
G1 X31.6520 Y2.4000 ; infill
G1 X31.6520 Y2.1820 ; infill
G1 X8.9030 Y2.1820 ; infill
G1 X8.1970 Y1.9630 ; infill
G1 X31.6520 Y1.9630 ; infill
G1 X31.6520 Y1.7450 ; infill
G1 X7.2870 Y1.7450 ; infill
G1 X6.3930 Y1.5960 ; infill
G1 X5.6810 Y1.5270 ; infill
G1 X31.6520 Y1.5270 ; infill
G1 X31.6520 Y1.3090 ; infill

Call togglePress P5; toggle off
G1 X-31.652 Y1.309 E2.96947 ; infill

G1 X-31.652 Y1.091 E2.97002 ; infill
Call togglePress P5; toggle on
G1 X31.6520 Y1.0910 ; infill
G1 X31.6520 Y0.8730 ; infill

Call togglePress P5; toggle off
G1 X-31.652 Y0.873 E3.28708 ; infill

G1 X-31.652 Y0.654 E3.28763 ; infill
Call togglePress P5; toggle on
G1 X31.6520 Y0.6540 ; infill
G1 X31.6520 Y0.4360 ; infill

Call togglePress P5; toggle off
G1 X-31.652 Y0.436 E3.60469 ; infill

G1 X-31.652 Y0.218 E3.60523 ; infill
Call togglePress P5; toggle on
G1 X31.6520 Y0.2180 ; infill
G1 X31.6520 Y0.0000 ; infill

Call togglePress P5; toggle off
G1 X-31.652 Y-0.000 E3.92230 ; infill

G1 X-31.652 Y-0.218 E3.92284 ; infill
G1 X31.652 Y-0.218 E4.08110 ; infill
G1 X31.652 Y-0.436 E4.08165 ; infill
G1 X-31.652 Y-0.436 E4.23991 ; infill
G1 X-31.652 Y-0.654 E4.24045 ; infill
G1 X31.652 Y-0.654 E4.39871 ; infill
G1 X31.652 Y-0.873 E4.39926 ; infill
G1 X-31.652 Y-0.873 E4.55752 ; infill
G1 X-31.652 Y-1.091 E4.55806 ; infill
G1 X31.652 Y-1.091 E4.71632 ; infill
G1 X31.652 Y-1.309 E4.71687 ; infill
G1 X-31.652 Y-1.309 E4.87513 ; infill
G1 X-31.652 Y-1.527 E4.87567 ; infill
G1 X-5.681 Y-1.527 E4.94060 ; infill
G1 X-6.393 Y-1.596 E4.94239 ; infill
G1 X-7.287 Y-1.745 E4.94465 ; infill
G1 X-31.652 Y-1.745 E5.00556 ; infill
G1 X-31.652 Y-1.963 E5.00611 ; infill
G1 X-8.197 Y-1.963 E5.06475 ; infill
G1 X-8.903 Y-2.182 E5.06659 ; infill
G1 X-31.652 Y-2.182 E5.12346 ; infill
G1 X-31.652 Y-2.400 E5.12401 ; infill
G1 X-9.497 Y-2.400 E5.17940 ; infill
G1 X-10.013 Y-2.618 E5.18080 ; infill
G1 X-31.652 Y-2.618 E5.23489 ; infill
G1 X-31.652 Y-2.836 E5.23544 ; infill
G1 X-10.472 Y-2.836 E5.28839 ; infill
G1 X-10.888 Y-3.054 E5.28956 ; infill
G1 X-31.652 Y-3.054 E5.34147 ; infill
G1 X-31.652 Y-3.272 E5.34202 ; infill
G1 X-11.271 Y-3.272 E5.39297 ; infill
G1 X-11.628 Y-3.491 E5.39401 ; infill
G1 X-31.652 Y-3.491 E5.44407 ; infill
G1 X-31.652 Y-3.709 E5.44462 ; infill
G1 X-11.963 Y-3.709 E5.49384 ; infill
G1 X-12.271 Y-3.927 E5.49478 ; infill
G1 X-31.652 Y-3.927 E5.54323 ; infill
G1 X-31.652 Y-4.145 E5.54378 ; infill
G1 X-12.563 Y-4.145 E5.59150 ; infill
G1 X-12.842 Y-4.363 E5.59239 ; infill
G1 X-31.652 Y-4.363 E5.63941 ; infill
G1 X-31.652 Y-4.581 E5.63996 ; infill
G1 X-13.100 Y-4.581 E5.68634 ; infill

 ; reset extrusion distance
G1 Z10.250 F600.000 ; lift Z
G1 X-5.681 Y1.527 F600.000 ; move to first infill point
G1 Z0.250 F600.000 ; restore layer Z

G1 F60
G1 X-31.652 Y1.527 E2.06493 ; infill
G1 X-31.652 Y1.745 E2.06547 ; infill
G1 X-7.287 Y1.745 E2.12638 ; infill
G1 X-8.197 Y1.963 E2.12873 ; infill
G1 X-31.652 Y1.963 E2.18736 ; infill
G1 X-31.652 Y2.182 E2.18791 ; infill
G1 X-8.903 Y2.182 E2.24478 ; infill
G1 X-9.497 Y2.400 E2.24636 ; infill
G1 X-31.652 Y2.400 E2.30175 ; infill
G1 X-31.652 Y2.618 E2.30229 ; infill
G1 X-10.013 Y2.618 E2.35639 ; infill
G1 X-10.472 Y2.836 E2.35766 ; infill
G1 X-31.652 Y2.836 E2.41061 ; infill
G1 X-31.652 Y3.054 E2.41116 ; infill
G1 X-10.888 Y3.054 E2.46306 ; infill
G1 X-11.271 Y3.272 E2.46417 ; infill
G1 X-31.652 Y3.272 E2.51512 ; infill
G1 X-31.652 Y3.491 E2.51566 ; infill
G1 X-11.628 Y3.491 E2.56572 ; infill
G1 X-11.963 Y3.709 E2.56672 ; infill
G1 X-31.652 Y3.709 E2.61594 ; infill
G1 X-31.652 Y3.927 E2.61649 ; infill
G1 X-12.271 Y3.927 E2.66494 ; infill
G1 X-12.563 Y4.145 E2.66585 ; infill
G1 X-31.652 Y4.145 E2.71357 ; infill
G1 X-31.652 Y4.363 E2.71412 ; infill
G1 X-12.842 Y4.363 E2.76114 ; infill
G1 X-13.100 Y4.581 E2.76199 ; infill
G1 X-31.652 Y4.581 E2.80837 ; infill
G1 Z0.500 F600.000 ; move to next layer (1)
G1 F60
G1 X-13.100 Y4.581 E2.85475 ; infill
G1 X-12.842 Y4.363 E2.85559 ; infill
G1 X-31.652 Y4.363 E2.90262 ; infill
G1 X-31.652 Y4.145 E2.90316 ; infill
G1 X-12.563 Y4.145 E2.95088 ; infill
G1 X-12.271 Y3.927 E2.95179 ; infill
G1 X-31.652 Y3.927 E3.00025 ; infill
G1 X-31.652 Y3.709 E3.00079 ; infill
G1 X-11.963 Y3.709 E3.05001 ; infill
G1 X-11.628 Y3.491 E3.05101 ; infill
G1 X-31.652 Y3.491 E3.10107 ; infill
G1 X-31.652 Y3.272 E3.10162 ; infill
G1 X-11.271 Y3.272 E3.15257 ; infill
G1 X-10.888 Y3.054 E3.15367 ; infill
G1 X-31.652 Y3.054 E3.20558 ; infill
G1 X-31.652 Y2.836 E3.20612 ; infill
G1 X-10.472 Y2.836 E3.25907 ; infill
G1 X-10.013 Y2.618 E3.26034 ; infill
G1 X-31.652 Y2.618 E3.31444 ; infill
G1 X-31.652 Y2.400 E3.31499 ; infill
G1 X-9.497 Y2.400 E3.37037 ; infill
G1 X-8.903 Y2.182 E3.37196 ; infill
G1 X-31.652 Y2.182 E3.42883 ; infill
G1 X-31.652 Y1.963 E3.42937 ; infill
G1 X-8.197 Y1.963 E3.48801 ; infill
G1 X-7.287 Y1.745 E3.49035 ; infill
G1 X-31.652 Y1.745 E3.55126 ; infill
G1 X-31.652 Y1.527 E3.55181 ; infill
G1 X-5.681 Y1.527 E3.61673 ; infill

 ; reset extrusion distance
G1 Z10.500 F600.000 ; lift Z
G1 X-13.100 Y-4.581 F600.000 ; move to first infill point
G1 Z0.500 F600.000 ; restore layer Z

G1 F60
G1 X-31.652 Y-4.581 E2.04638 ; infill
G1 X-31.652 Y-4.363 E2.04692 ; infill
G1 X-12.842 Y-4.363 E2.09395 ; infill
G1 X-12.563 Y-4.145 E2.09484 ; infill
G1 X-31.652 Y-4.145 E2.14256 ; infill
G1 X-31.652 Y-3.927 E2.14310 ; infill
G1 X-12.271 Y-3.927 E2.19156 ; infill
G1 X-11.963 Y-3.709 E2.19250 ; infill
G1 X-31.652 Y-3.709 E2.24172 ; infill
G1 X-31.652 Y-3.491 E2.24226 ; infill
G1 X-11.628 Y-3.491 E2.29232 ; infill
G1 X-11.271 Y-3.272 E2.29337 ; infill
G1 X-31.652 Y-3.272 E2.34432 ; infill
G1 X-31.652 Y-3.054 E2.34487 ; infill
G1 X-10.888 Y-3.054 E2.39677 ; infill
G1 X-10.472 Y-2.836 E2.39795 ; infill
G1 X-31.652 Y-2.836 E2.45090 ; infill
G1 X-31.652 Y-2.618 E2.45144 ; infill
G1 X-10.013 Y-2.618 E2.50554 ; infill
G1 X-9.497 Y-2.400 E2.50694 ; infill
G1 X-31.652 Y-2.400 E2.56233 ; infill
G1 X-31.652 Y-2.182 E2.56287 ; infill
G1 X-8.903 Y-2.182 E2.61975 ; infill
G1 X-8.197 Y-1.963 E2.62159 ; infill
G1 X-31.652 Y-1.963 E2.68023 ; infill
G1 X-31.652 Y-1.745 E2.68077 ; infill
G1 X-7.287 Y-1.745 E2.74169 ; infill
G1 X-6.393 Y-1.596 E2.74395 ; infill
G1 X-5.681 Y-1.527 E2.74574 ; infill
G1 X-31.652 Y-1.527 E2.81067 ; infill
G1 X-31.652 Y-1.309 E2.81121 ; infill
G1 X31.652 Y-1.309 E2.96947 ; infill
G1 X31.652 Y-1.091 E2.97002 ; infill
G1 X-31.652 Y-1.091 E3.12828 ; infill
G1 X-31.652 Y-0.873 E3.12882 ; infill
G1 X31.652 Y-0.873 E3.28708 ; infill
G1 X31.652 Y-0.654 E3.28763 ; infill
G1 X-31.652 Y-0.654 E3.44589 ; infill
G1 X-31.652 Y-0.436 E3.44643 ; infill
G1 X31.652 Y-0.436 E3.60469 ; infill
G1 X31.652 Y-0.218 E3.60524 ; infill
G1 X-31.652 Y-0.218 E3.76349 ; infill
G1 X-31.652 Y-0.000 E3.76404 ; infill
Call togglePress P5; toggle on
G1 X31.6520 Y0.0000 ; infill
G1 X31.6520 Y0.2180 ; infill

Call togglePress P5; toggle off
G1 X-31.652 Y0.218 E4.08110 ; infill

G1 X-31.652 Y0.436 E4.08165 ; infill
Call togglePress P5; toggle on
G1 X31.6520 Y0.4360 ; infill
G1 X31.6520 Y0.6540 ; infill

Call togglePress P5; toggle off
G1 X-31.652 Y0.654 E4.39871 ; infill

G1 X-31.652 Y0.873 E4.39926 ; infill
Call togglePress P5; toggle on
G1 X31.6520 Y0.8730 ; infill
G1 X31.6520 Y1.0910 ; infill

Call togglePress P5; toggle off
G1 X-31.652 Y1.091 E4.71632 ; infill

G1 X-31.652 Y1.309 E4.71687 ; infill
Call togglePress P5; toggle on
G1 X31.6520 Y1.3090 ; infill
G1 X31.6520 Y1.5270 ; infill
G1 X5.6810 Y1.5270 ; infill
G1 X6.3930 Y1.5960 ; infill
G1 X7.2870 Y1.7450 ; infill
G1 X31.6520 Y1.7450 ; infill
G1 X31.6520 Y1.9630 ; infill
G1 X8.1970 Y1.9630 ; infill
G1 X8.9030 Y2.1820 ; infill
G1 X31.6520 Y2.1820 ; infill
G1 X31.6520 Y2.4000 ; infill
G1 X9.4970 Y2.4000 ; infill
G1 X10.0130 Y2.6180 ; infill
G1 X31.6520 Y2.6180 ; infill
G1 X31.6520 Y2.8360 ; infill
G1 X10.4720 Y2.8360 ; infill
G1 X10.8880 Y3.0540 ; infill
G1 X31.6520 Y3.0540 ; infill
G1 X31.6520 Y3.2720 ; infill
G1 X11.2710 Y3.2720 ; infill
G1 X11.6280 Y3.4910 ; infill
G1 X31.6520 Y3.4910 ; infill
G1 X31.6520 Y3.7090 ; infill
G1 X11.9630 Y3.7090 ; infill
G1 X12.2710 Y3.9270 ; infill
G1 X31.6520 Y3.9270 ; infill
G1 X31.6520 Y4.1450 ; infill
G1 X12.5630 Y4.1450 ; infill
G1 X12.8420 Y4.3630 ; infill
G1 X31.6520 Y4.3630 ; infill
G1 X31.6520 Y4.5810 ; infill
G1 X13.1000 Y4.5810 ; infill

Call togglePress P5; toggle off


 ; reset extrusion distance
G1 Z10.500 F600.000 ; lift Z
G1 X5.681 Y-1.527 F600.000 ; move to first infill point
G1 Z0.500 F600.000 ; restore layer Z

G1 F60
G1 X31.652 Y-1.527 E2.06493 ; infill
G1 X31.652 Y-1.745 E2.06547 ; infill
G1 X7.287 Y-1.745 E2.12638 ; infill
G1 X8.197 Y-1.963 E2.12873 ; infill
G1 X31.652 Y-1.963 E2.18736 ; infill
G1 X31.652 Y-2.182 E2.18791 ; infill
G1 X8.903 Y-2.182 E2.24478 ; infill
G1 X9.497 Y-2.400 E2.24636 ; infill
G1 X31.652 Y-2.400 E2.30175 ; infill
G1 X31.652 Y-2.618 E2.30229 ; infill
G1 X10.013 Y-2.618 E2.35639 ; infill
G1 X10.472 Y-2.836 E2.35766 ; infill
G1 X31.652 Y-2.836 E2.41061 ; infill
G1 X31.652 Y-3.054 E2.41116 ; infill
G1 X10.888 Y-3.054 E2.46306 ; infill
G1 X11.271 Y-3.272 E2.46417 ; infill
G1 X31.652 Y-3.272 E2.51512 ; infill
G1 X31.652 Y-3.491 E2.51566 ; infill
G1 X11.628 Y-3.491 E2.56572 ; infill
G1 X11.963 Y-3.709 E2.56672 ; infill
G1 X31.652 Y-3.709 E2.61594 ; infill
G1 X31.652 Y-3.927 E2.61649 ; infill
G1 X12.271 Y-3.927 E2.66494 ; infill
G1 X12.563 Y-4.145 E2.66585 ; infill
G1 X31.652 Y-4.145 E2.71357 ; infill
G1 X31.652 Y-4.363 E2.71412 ; infill
G1 X12.842 Y-4.363 E2.76114 ; infill
G1 X13.100 Y-4.581 E2.76199 ; infill
G1 X31.652 Y-4.581 E2.80837 ; infill

 ; reset extrusion distance
G1 Z10.500 F600.000 ; lift Z



; filament used = 10.6mm (0.2cm3)
; total filament cost = 0.0

; avoid_crossing_perimeters = 0
; bed_shape = -175x-175,175x-175,175x175,-175x175
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_connections_width = 0
; brim_width = 0
; complete_objects = 0
; cooling = 0
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_filament_gcode = ""
; end_gcode = 
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #00FF00
; filament_cost = 0
; filament_density = 0
; filament_diameter = 5
; filament_max_volumetric_speed = 0
; filament_notes = ""
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0.25
; first_layer_speed = 1
; first_layer_temperature = 0
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; has_heatbed = 0
; infill_acceleration = 0
; infill_first = 0
; interior_brim_width = 0
; layer_gcode = 
; max_fan_speed = 100
; max_layer_height = 0.3
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.15
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 0.25
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; printer_notes = 
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 10
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; skirt_distance = 0
; skirt_height = 1
; skirts = 0
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = ""
; start_gcode = 
; temperature = 0
; threads = 12
; toolchange_gcode = 
; travel_speed = 10
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_set_and_wait_bed = 0
; use_set_and_wait_extruder = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = 0
; z_steps_per_mm = 0
; adaptive_slicing = 0
; adaptive_slicing_quality = 75%
; dont_support_bridges = 1
; extrusion_width = 0.25
; first_layer_height = 0.25
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.25
; match_horizontal_surfaces = 0
; raft_layers = 0
; regions_overlap = 0
; seam_position = aligned
; sequential_print_priority = 0
; support_material = 0
; support_material_angle = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_extrusion_width = 0
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_max_layers = 0
; support_material_pattern = pillars
; support_material_spacing = 2.5
; support_material_speed = 77
; support_material_threshold = 60%
; xy_size_compensation = 0
; bottom_infill_pattern = rectilinear
; bottom_solid_layers = 0
; bridge_flow_ratio = 1
; bridge_speed = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 7
; external_perimeters_first = 0
; extra_perimeters = 0
; fill_angle = 0
; fill_density = 90%
; fill_gaps = 0
; fill_pattern = alignedrectilinear
; gap_fill_speed = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.25
; infill_overlap = 0
; infill_speed = 1
; overhangs = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 7
; perimeters = 0
; small_perimeter_speed = 7
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; thin_walls = 0
; top_infill_extrusion_width = 0
; top_infill_pattern = rectilinear
; top_solid_infill_speed = 15
; top_solid_layers = 0
SECONDS

M2

;##########Functions############;
DFS setPress

        $strtask1 = DBLTOSTR( $P, 0 )
        $strtask1 = "COM" + $strtask1
        $hFile = FILEOPEN $strtask1, 2
        COMMINIT $hFile, "baud=115200 parity=N data=8 stop=1"
        COMMSETTIMEOUT $hFile, -1, -1, 1000

        $press = $Q * 10.0
        $strtask2 = DBLTOSTR( $press , 0 )


        $length = STRLEN( $strtask2 )
        WHILE $length < 4.0
                $strtask2 = "0" + $strtask2
                $length = STRLEN( $strtask2 )
        ENDWHILE


        $strtask2 = "08PS  " + $strtask2

        $cCheck = 0.00
        $lame = STRTOASCII ($strtask2, 0)
        $cCheck = $cCheck - $lame
        $lame = STRTOASCII( $strtask2, 1)
        $cCheck = $cCheck - $lame
        $lame = STRTOASCII( $strtask2, 2)
        $cCheck = $cCheck - $lame
        $lame = STRTOASCII( $strtask2, 3)
        $cCheck = $cCheck - $lame
        $lame = STRTOASCII( $strtask2, 4)
        $cCheck = $cCheck - $lame
        $lame = STRTOASCII( $strtask2, 5)
        $cCheck = $cCheck - $lame
        $lame = STRTOASCII( $strtask2, 6)
        $cCheck = $cCheck - $lame
        $lame = STRTOASCII( $strtask2, 7)
        $cCheck = $cCheck - $lame
        $lame = STRTOASCII( $strtask2, 8)
        $cCheck = $cCheck - $lame
        $lame = STRTOASCII( $strtask2, 9)
        $cCheck = $cCheck - $lame

        WHILE( $cCheck) < 0
                $cCheck = $cCheck + 256
        ENDWHILE


        $strtask3 = makestring "{#H}" $cCheck
        $strtask3 = STRUPR( $strtask3 )
        $strtask2 = "" + $strtask2 + $strtask3 + ""

        FILEWRITE $hFile ""
        FILEWRITE $hFile $strtask2
        FILEWRITE $hFile ""


        FILECLOSE $hFile


ENDDFS

DFS togglePress

        $strtask1 = DBLTOSTR( $P, 0 )
        $strtask1 = "COM" + $strtask1
        $hFile = FILEOPEN $strtask1, 2
        COMMINIT $hFile, "baud=115200 parity=N data=8 stop=1"
        COMMSETTIMEOUT $hFile, -1, -1, 1000


        $strtask2 = "04DI  "

        $cCheck = 0.00
        $lame = STRTOASCII ($strtask2, 0)
        $cCheck = $cCheck - $lame
        $lame = STRTOASCII( $strtask2, 1)
        $cCheck = $cCheck - $lame
        $lame = STRTOASCII( $strtask2, 2)
        $cCheck = $cCheck - $lame
        $lame = STRTOASCII( $strtask2, 3)
        $cCheck = $cCheck - $lame
        $lame = STRTOASCII( $strtask2, 4)
        $cCheck = $cCheck - $lame
        $lame = STRTOASCII( $strtask2, 5)
        $cCheck = $cCheck - $lame

        WHILE( $cCheck) < 0
                $cCheck = $cCheck + 256
        ENDWHILE


        $strtask3 = makestring "{#H}" $cCheck
        $strtask3 = STRUPR( $strtask3 )
        $strtask2 = "" + $strtask2 + $strtask3 + ""

        FILEWRITE $hFile ""
        FILEWRITE $hFile $strtask2
        FILEWRITE $hFile ""


        FILECLOSE $hFile
        G4 P0.15

ENDDFS

